### ISSUE TITLE
Allowframebreaks

### ISSUE THREAD

**Issue by antoine-germain** [pmichaillat/latex-presentation#1]
Hi Pascal, thanks again for the templates. I encountered a bug when trying to break the frames using [allowframebreaks]
When I use it, the title on the second frame does not carry over very well. 

```
\documentclass[12pt]{beamer}

\usepackage{presentation}
\usepackage{lipsum}

\begin{document}

\begin{frame}[allowframebreaks]{Title issue with frame breaks}
    \lipsum[2-3]
\end{frame}

\end{document}
```

For information, my compiler is pdfLaTeX and TeX live version is 2022.
Thanks again!

**Comment by pmichaillat** [comment]
I have just completed an update of the template, and the `allowframebreaks` command seems to work now. In `presentation.tex` I added the following, very long slide:

````
\begin{frame}[allowframebreaks]
\frametitle{Slide title: sunt in culpa qui officia deserunt mollit anim id est laborum}
\begin{itemize}
\item Lorem 
\item ipsum 
\item dolor 
\item sit 
\item amet
\item consectetur 
\item adipisicing 
\item elit
\item sed
\item do
\item eiusmod
\item tempor
\item incididunt
\item ut
\item labore
\item et 
\item dolore 
\item magna 
\item aliqua
\item Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident.
\end{itemize}
\end{frame}
````

I obtained the 3 following slides:

<img width="504" alt="Screenshot 2023-09-07 at 12 37 23" src="https://github.com/pmichaillat/latex-presentation/assets/85443660/c8119976-2b97-46e7-820f-4d70990619ca">
<img width="499" alt="Screenshot 2023-09-07 at 12 37 28" src="https://github.com/pmichaillat/latex-presentation/assets/85443660/1f390433-2443-4e81-adbf-f14d28b60943">
<img width="503" alt="Screenshot 2023-09-07 at 12 37 34" src="https://github.com/pmichaillat/latex-presentation/assets/85443660/b0e70f84-aacb-45cb-98c4-4e74185ff72f">

So the breaks worked perfectly, and the frame titles were appended with the Roman numerals I, II, and III.

Can you check if the updated template solves your problems?
