### ISSUE TITLE
Compile error on ubuntu22.04

### ISSUE THREAD

**Issue by forieux** [pmichaillat/latex-presentation#2]
First thanks for this clean template. I try to use it on Ubuntu 22.04 and texlive 2021 and I have this error

`
\onehalfspacing ...stretch {1.25}\ifcase \@ptsize 
                                                  \relax \setstretch {1.25}\...l.41 \setbeamertemplate
                       {title page}[default][left,leftskip=-8pt]
./presentation.sty:41: Missing number, treated as zero.
<to be read again> 
                   \relax 
l.41 \setbeamertemplate
                       {title page}[default][left,leftskip=-8pt]
`
I'm not fluent in latex, do you have an idea ?

**Comment by pmichaillat** [comment]
Bonjour Francois,

I am not sure what it could be. The template compiles without error on my machine. Here are a couple of things to try:

+ Update Texlive to the 2023 version. There might be an issue with the older versions of the packages.
+ From the error message, it looks like the issue might come from the `onehalfspacing` option in the `setspace` package. So try replacing line 40 by `\usepackage{setspace}`. If that works, you can control spacing with the command `\setstretch{1.25}`.
+ If the template still refuses to compile, try commenting line 41 `\setbeamertemplate{title page}[default][left,leftskip=-8pt]`. It is not necessary for the template to work, so try to see what happens. 

Let me know what you find. If nothing works, maybe the new error messages will help finding the source of the problem.

**Comment by forieux** [comment]
Bonjour !

I effectively removed the `\usepackage{setspace}` to fix the issue. Adding it again with `\setstrech{1.25}` fixes the bug, thank you !
