### ISSUE TITLE
Remove page number from the title slide

### ISSUE THREAD

**Issue by reyhanhgh** [pmichaillat/latex-presentation#3]
Hi Pascal,
Thank you for sharing your neat template. I would like to remove the page number from only the title page. I tried several things such as redefinition of the footnote for the title page but they did not work. Would you have any suggestions?
Thanks!

**Comment by reyhanhgh** [comment]
Another question: how can i restart slide numbering for the backup slides? I want that the backup slides to start at their own 1. Merci beaucoup :-)

**Comment by pmichaillat** [comment]
To remove the page number from the title slide only, 
use `\frame[plain]{\titlepage}` instead of `\frame{\titlepage}` on line 19 of `presentation.tex`. The page numbers will start appearing on the second slide.

**Comment by pmichaillat** [comment]
To restart numbering for the backup slides, just add `\addtocounter{framenumber}{-18}` on line 201 in `presentation.tex`, just under the `\lastslide` command. This will remove 18 from the frame counter, so the frame number will restart at 1 (19 - 18), and the total number of frames will be just 2 (20 - 18). 

Of course you need to adjust 18 based on the number of frames in the main body of the presentation.

**Comment by reyhanhgh** [comment]
Thank you very much Pascal for your quick responses. I appreciate.
