### ISSUE TITLE
itemize settings

### ISSUE THREAD

**Issue by reyhanhgh** [pmichaillat/latex-presentation#5]
Hi Pascal,

 I am encountering difficulties while attempting to use the `\usepackage{enumitem} `package within the template, which is preventing me from making adjustments to the `itemize` settings. I am looking to remove the white space before the bullets in the `itemize` environment within some text color boxes, as shown in the image below:

<img width="310" alt="Screen Shot 2023-12-05 at 19 41 49" src="https://github.com/pmichaillat/latex-presentation/assets/4801109/b5e3dbd8-ff74-4ccb-ba1f-7ba826e920d9">

using:
```
\begin{frame}
\frametitle{research framework}
\centering
\includegraphics[width=0.825\textwidth]{figures/framework.pdf}

\begin{tikzpicture}[remember picture,overlay]
    \node[fill=white, text width=5cm, align=center, inner sep=2pt, draw=black, text=black, font=\sffamily\small] at (3.5,4) {
        \begin{minipage}{5cm} 
            In both spaces:
            \begin{itemize}
                \item Conceptual Benchmark\\ 
                \item Performance Metric:\\
                KGE \citep{gupta2009}
            \end{itemize}
        \end{minipage}
    };
\end{tikzpicture}

\end{frame}
```
From my research, it appears that most solutions to this issue involve utilizing commands from the `enumitem` package. However, due to the current limitations of my template, I am unable to use this package.

I was wondering if you could suggest any workarounds or alternative approaches to achieve the desired formatting. 
Thank you very much

**Comment by pmichaillat** [comment]
Yes, the `enumitem` package does not work with the Beamer class, so I could not use it in the template (although it is a great package, which I use in [my paper template](https://github.com/pmichaillat/latex-paper)).

The Beamer class offers commands to modify lists directly without resorting to other packages. For instance in the template I use the following modifications:

````tex
\setbeamertemplate{itemize item}{\textbullet}
\setbeamertemplate{itemize subitem}{\textendash} 
\setbeamertemplate{enumerate item}[default]
\setbeamertemplate{enumerate subitem}[default]
\setbeamertemplate{enumerate subitem}{\alph{enumii}.}
````

The `setbeamertemplate` command might be all you need. 

I have also found a few posts describing the conflicts between `enumitem` and Beamer, and explaining how to produce sophisticated lists with Beamer:

+ https://tex.stackexchange.com/questions/31505/trouble-combining-enumitem-and-beamer
+ https://tex.stackexchange.com/questions/356795/enumitem-breaks-beamers-itemize-despite-fixes
+ https://stackoverflow.com/questions/2611276/latex-beamer-way-to-change-the-bullet-indentation
+ https://copyprogramming.com/howto/checklist-in-beamer-using-enumitem-package

These posts might contain useful additional information.

Good luck, and let me know what you find.
